backend:
  name: git-gateway
  branch: main  # Nome da branch principal do GitHub

media_folder: "static/imagens"  # Mudança no caminho para ficar no diretório 'static'
public_folder: "/imagens"

collections:
  - name: "posts"
    label: "Postagens"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Título", widget: "string" }
      - { name: "date", label: "Data", widget: "datetime" }
      - { name: "body", label: "Conteúdo", widget: "markdown" }
